name: Build
on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  nuitka:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8
      - run: pip install nuitka
      - run: python -m nuitka --standalone --onefile --output-filename="test.exe" --output-dir="build" --assume-yes-for-downloads run.py
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}
          path: build/test.exe
