name: Build
on:
  release:
    types:
      - created
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nuitka:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          #- "3.7"
          #- "3.6"
          #- "3.5"
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4.1.1
      - name: 设置 msvc
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          sdk: 10
          toolset: 14.3
      - name: 设置 Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: 安装依赖
        run: pip install nuitka zstandard ordered-set
      - name: 编译
        run: python -m nuitka --standalone --onefile --output-filename="test.exe" --output-dir="build" run.py
      - name: 上传
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.python-version }}
          path: build/test.exe
