name: Ubuntu
on:
  workflow_dispatch:

jobs:
  nuitka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          # - "3.8"
          #- "3.7"
          #- "3.6"
          #- "3.5"
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4.1.1
      - name: Mingw64
        run:
          sudo apt-get install mingw-w64
      - name: 设置 Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: 安装依赖
        run: pip install nuitka zstandard ordered-set
      - name: 编译
        run: python -m nuitka --jobs=8 --standalone --onefile --output-dir="build" --main="run.py"
      - name: 上传
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.python-version }}
          path: build
